code --install-extension aaron-bond.better-comments
code --install-extension alexcvzz.vscode-sqlite
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension jdinhlife.gruvbox
code --install-extension miguelsolorio.fluent-icons
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.debugpy
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode.live-server
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension pkief.material-icon-theme
code --install-extension usernamehw.errorlens
code --install-extension visualstudioexptteam.intellicode-api-usage-examples
code --install-extension visualstudioexptteam.vscodeintellicode
